# Pre-commit hooks for code quality
# Install with: pre-commit install
# Run manually with: pre-commit run --all-files

repos:
  # Ruff - Fast Python linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4  # Use latest stable version
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
        types_or: [python, pyi]

      # Run the formatter
      - id: ruff-format
        types_or: [python, pyi]

  # Additional helpful hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Prevent committing large files
      - id: check-added-large-files
        args: ["--maxkb=1000"]

      # Check for merge conflict markers
      - id: check-merge-conflict

      # Check YAML syntax
      - id: check-yaml
        args: [--unsafe]  # Allow custom YAML tags

      # Check TOML syntax
      - id: check-toml

      # Check JSON syntax
      - id: check-json

      # Ensure files end with newline
      - id: end-of-file-fixer

      # Trim trailing whitespace
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

      # Check for files that would conflict on case-insensitive filesystems
      - id: check-case-conflict

      # Detect private keys
      - id: detect-private-key
