services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: echolens-postgres
    environment:
      POSTGRES_USER: echolens
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: echolens
    volumes:
      - echolens_postgres_data:/var/lib/postgresql/data
      - ./migrations:/migrations  # Mount migrations for easy access
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U echolens"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - backend-network

  redis:
    image: redis:7-alpine
    container_name: echolens-redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - echolens_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - backend-network

  echolens-backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: echolens-backend
    # No ports exposed - backend is private, accessed via Next.js API proxy
    volumes:
      - ./echolens_data:/app/echolens_data
      - ./task_logs:/app/task_logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://echolens:${POSTGRES_PASSWORD}@postgres:5432/echolens
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD}@redis:6379/0
    env_file:
      - .env.prod
    restart: always
    networks:
      - backend-network
      - frontend-network

  celery-worker:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: echolens-celery-worker
    command: sh -c ". .venv/bin/activate && celery -A app.celery_app worker --loglevel=info --concurrency=${CELERY_WORKER_CONCURRENCY:-2}"
    volumes:
      - ./echolens_data:/app/echolens_data
      - ./task_logs:/app/task_logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://echolens:${POSTGRES_PASSWORD}@postgres:5432/echolens
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD}@redis:6379/0
    env_file:
      - .env.prod
    restart: always
    networks:
      - backend-network

  celery-beat:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: echolens-celery-beat
    command: sh -c ". .venv/bin/activate && celery -A app.celery_app beat --loglevel=info"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://echolens:${POSTGRES_PASSWORD}@postgres:5432/echolens
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD}@redis:6379/0
    env_file:
      - .env.prod
    restart: always
    networks:
      - backend-network

  echolens-frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: /api/proxy
    image: echolens-frontend:prod
    container_name: echolens-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - NEXT_PUBLIC_API_URL=/api/proxy
      - BACKEND_URL=http://echolens-backend:8000  # Internal backend URL for server-side proxy
    depends_on:
      - echolens-backend
    restart: always
    networks:
      - frontend-network

volumes:
  echolens_postgres_data:
  echolens_redis_data:

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge
